# Generated by Django 5.1 on 2025-11-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MockVehicleData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(max_length=20, verbose_name="license plate"),
                ),
                ("state", models.CharField(max_length=2, verbose_name="state")),
                (
                    "vin",
                    models.CharField(
                        db_index=True, max_length=17, unique=True, verbose_name="VIN"
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="year")),
                ("make", models.CharField(max_length=100, verbose_name="make")),
                ("model", models.CharField(max_length=100, verbose_name="model")),
                (
                    "trim",
                    models.CharField(blank=True, max_length=100, verbose_name="trim"),
                ),
                (
                    "body_style",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="body style"
                    ),
                ),
                (
                    "glass_parts",
                    models.JSONField(default=dict, verbose_name="glass parts data"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "mock vehicle data",
                "verbose_name_plural": "mock vehicle data",
                "indexes": [
                    models.Index(
                        fields=["license_plate", "state"],
                        name="vehicles_mo_license_0ffa22_idx",
                    ),
                    models.Index(fields=["vin"], name="vehicles_mo_vin_9ec0b8_idx"),
                ],
                "unique_together": {("license_plate", "state")},
            },
        ),
    ]
