# Generated by Django 5.1 on 2025-12-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoboltAPICache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("vin_decode", "VIN Decode"),
                            ("plate_decode", "Plate Decode"),
                            ("part_lookup", "Part Lookup"),
                        ],
                        max_length=20,
                        verbose_name="request type",
                    ),
                ),
                (
                    "request_key",
                    models.CharField(
                        db_index=True,
                        help_text="VIN, plate+state (e.g., 'ABC1234:WA'), or OEM part number",
                        max_length=100,
                        verbose_name="request key",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[("US", "United States"), ("CA", "Canada")],
                        default="US",
                        max_length=2,
                        verbose_name="country",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("Windshield", "Windshield"), ("Back", "Back Glass")],
                        default="Windshield",
                        max_length=20,
                        verbose_name="glass kind",
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        help_text="Full JSON response from AUTOBOLT API",
                        verbose_name="response data",
                    ),
                ),
                (
                    "http_status",
                    models.IntegerField(
                        help_text="HTTP status code from API response",
                        verbose_name="HTTP status code",
                    ),
                ),
                (
                    "vin",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Extracted VIN (from plate decode or VIN decode)",
                        max_length=17,
                        null=True,
                        verbose_name="VIN",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="year"
                    ),
                ),
                (
                    "make",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="make"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="model"
                    ),
                ),
                (
                    "nags_part_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Primary NAGS/AM part number (e.g., FW04316GTYN)",
                        max_length=20,
                        null=True,
                        verbose_name="NAGS part number",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Cache expiration (default: 30 days from creation)",
                        verbose_name="expires at",
                    ),
                ),
            ],
            options={
                "verbose_name": "AUTOBOLT API cache",
                "verbose_name_plural": "AUTOBOLT API cache entries",
                "indexes": [
                    models.Index(
                        fields=["request_key", "request_type"],
                        name="vehicles_au_request_16f4cf_idx",
                    ),
                    models.Index(fields=["vin"], name="vehicles_au_vin_b8e221_idx"),
                    models.Index(
                        fields=["nags_part_number"],
                        name="vehicles_au_nags_pa_5a6273_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="vehicles_au_expires_ee9fb9_idx"
                    ),
                ],
                "unique_together": {("request_type", "request_key", "country", "kind")},
            },
        ),
    ]
