# Generated by Django 5.1 on 2025-12-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_autoboltapicache"),
    ]

    operations = [
        migrations.CreateModel(
            name="NAGSCategory",
            fields=[
                (
                    "cat_cd",
                    models.IntegerField(
                        db_column="CAT_CD", primary_key=True, serialize=False
                    ),
                ),
                ("dsc", models.CharField(db_column="DSC", max_length=50)),
            ],
            options={
                "db_table": "dbo.CATEGORY",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NAGSGlass",
            fields=[
                (
                    "nags_glass_id",
                    models.CharField(
                        db_column="NAGS_GLASS_ID",
                        help_text="NAGS glass part ID (e.g., 'DW04567')",
                        max_length=7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prefix_cd",
                    models.CharField(
                        db_column="PREFIX_CD",
                        help_text="Glass category prefix (DW, DT, FW, FT, etc.)",
                        max_length=2,
                    ),
                ),
                (
                    "part_num",
                    models.IntegerField(
                        db_column="PART_NUM", help_text="Numeric part number"
                    ),
                ),
                (
                    "ant_flag",
                    models.CharField(
                        blank=True,
                        db_column="ANT_FLAG",
                        help_text="Has antenna (Y/N)",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "blk_size1",
                    models.DecimalField(
                        blank=True,
                        db_column="BLK_SIZE1",
                        decimal_places=2,
                        help_text="Block dimension 1",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "blk_size2",
                    models.DecimalField(
                        blank=True,
                        db_column="BLK_SIZE2",
                        decimal_places=2,
                        help_text="Block dimension 2",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "encap_flag",
                    models.CharField(
                        blank=True,
                        db_column="ENCAP_FLAG",
                        help_text="Encapsulated glass (Y/N)",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "hds_up_disp_flag",
                    models.CharField(
                        blank=True,
                        db_column="HDS_UP_DISP_FLAG",
                        help_text="Heads-up display (Y/N)",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "heated_flag",
                    models.CharField(
                        blank=True,
                        db_column="HEATED_FLAG",
                        help_text="Heated glass (Y/N)",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "num_holes",
                    models.CharField(
                        blank=True,
                        db_column="NUM_HOLES",
                        help_text="Number of holes",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "slider_flag",
                    models.CharField(
                        blank=True,
                        db_column="SLIDER_FLAG",
                        help_text="Sliding window (Y/N)",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "solar_flag",
                    models.CharField(
                        blank=True,
                        db_column="SOLAR_FLAG",
                        help_text="Solar coating (Y/N)",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "superseding_dt",
                    models.CharField(
                        blank=True,
                        db_column="SUPERSEDING_DT",
                        help_text="Date this part was superseded",
                        max_length=19,
                        null=True,
                    ),
                ),
                (
                    "superseding_nags_glass_id",
                    models.CharField(
                        blank=True,
                        db_column="SUPERSEDING_NAGS_GLASS_ID",
                        help_text="Replacement part ID",
                        max_length=7,
                        null=True,
                    ),
                ),
                (
                    "thickness",
                    models.CharField(
                        blank=True,
                        db_column="THICKNESS",
                        help_text="Glass thickness",
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "wt",
                    models.CharField(
                        blank=True,
                        db_column="WT",
                        help_text="Weight",
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "tube_qty",
                    models.DecimalField(
                        blank=True,
                        db_column="TUBE_QTY",
                        decimal_places=1,
                        help_text="Urethane tube quantity needed",
                        max_digits=2,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "dbo.NAGS_GLASS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NAGSGlassDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nags_glass_id",
                    models.CharField(
                        db_column="NAGS_GLASS_ID", db_index=True, max_length=7
                    ),
                ),
                (
                    "atchmnt_flag",
                    models.CharField(
                        blank=True, db_column="ATCHMNT_FLAG", max_length=1, null=True
                    ),
                ),
                (
                    "glass_color_cd",
                    models.CharField(
                        blank=True, db_column="GLASS_COLOR_CD", max_length=2, null=True
                    ),
                ),
                (
                    "prem_flag",
                    models.CharField(
                        blank=True, db_column="PREM_FLAG", max_length=1, null=True
                    ),
                ),
            ],
            options={
                "db_table": "dbo.NAGS_GLASS_DET",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NAGSGlassPrice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nags_glass_id",
                    models.CharField(
                        db_column="NAGS_GLASS_ID",
                        db_index=True,
                        help_text="FK to NAGS_GLASS",
                        max_length=7,
                    ),
                ),
                (
                    "atchmnt_flag",
                    models.CharField(
                        blank=True,
                        db_column="ATCHMNT_FLAG",
                        help_text="Attachment flag (Y/N)",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "glass_color_cd",
                    models.CharField(
                        db_column="GLASS_COLOR_CD",
                        help_text="Color code (GT=Green Tint, etc.)",
                        max_length=2,
                    ),
                ),
                (
                    "prem_flag",
                    models.CharField(
                        blank=True,
                        db_column="PREM_FLAG",
                        help_text="Premium flag (Y/N)",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "region_cd",
                    models.CharField(
                        db_column="REGION_CD", help_text="Region (U=US)", max_length=1
                    ),
                ),
                (
                    "eff_dt",
                    models.CharField(
                        db_column="EFF_DT",
                        help_text="Effective date (YYYYMMDD format)",
                        max_length=19,
                    ),
                ),
                (
                    "avail_cd",
                    models.CharField(
                        blank=True,
                        db_column="AVAIL_CD",
                        help_text="Availability code (H=Historical, A=Active)",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "prc",
                    models.DecimalField(
                        db_column="PRC",
                        decimal_places=2,
                        help_text="NAGS LIST PRICE",
                        max_digits=6,
                    ),
                ),
                (
                    "prc_status_cd",
                    models.CharField(
                        db_column="PRC_STATUS_CD",
                        help_text="Price status (NP=No Price, A=Active)",
                        max_length=3,
                    ),
                ),
                (
                    "spcl_prc_cd",
                    models.CharField(
                        blank=True,
                        db_column="SPCL_PRC_CD",
                        help_text="Special price code",
                        max_length=1,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "dbo.NAGS_GLASS_PRC",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NAGSHardware",
            fields=[
                (
                    "nags_hw_id",
                    models.CharField(
                        db_column="NAGS_HW_ID",
                        help_text="Hardware part ID (e.g., 'HAH000004')",
                        max_length=9,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hw_type_cd",
                    models.CharField(
                        db_column="HW_TYPE_CD",
                        help_text="Hardware type code (FK to HW_TYPE)",
                        max_length=2,
                    ),
                ),
                (
                    "hw_num",
                    models.IntegerField(
                        db_column="HW_NUM", help_text="Hardware number"
                    ),
                ),
                (
                    "superseding_dt",
                    models.CharField(
                        blank=True, db_column="SUPERSEDING_DT", max_length=19, null=True
                    ),
                ),
                (
                    "superseding_hw_id",
                    models.CharField(
                        blank=True,
                        db_column="SUPERSEDING_HW_ID",
                        max_length=9,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "dbo.NAGS_HW",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NAGSHardwarePrice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nags_hw_id",
                    models.CharField(
                        db_column="NAGS_HW_ID", db_index=True, max_length=9
                    ),
                ),
                (
                    "hw_color_cd",
                    models.CharField(
                        db_column="HW_COLOR_CD",
                        help_text="Color code (NA=Not Applicable)",
                        max_length=2,
                    ),
                ),
                ("region_cd", models.CharField(db_column="REGION_CD", max_length=1)),
                (
                    "prc",
                    models.DecimalField(
                        db_column="PRC",
                        decimal_places=2,
                        help_text="LIST PRICE",
                        max_digits=4,
                    ),
                ),
                ("eff_dt", models.CharField(db_column="EFF_DT", max_length=19)),
                (
                    "prc_status_cd",
                    models.CharField(
                        db_column="PRC_STATUS_CD",
                        help_text="Price status (A=Active)",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "db_table": "dbo.NAGS_HW_PRC",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NAGSHardwareType",
            fields=[
                (
                    "hw_type_cd",
                    models.CharField(
                        db_column="HW_TYPE_CD",
                        max_length=2,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dsc",
                    models.CharField(
                        db_column="DSC", help_text="Description", max_length=100
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        blank=True,
                        db_column="USAGE",
                        help_text="M=Major part, I=Installation item",
                        max_length=1,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "dbo.HW_TYPE",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NAGSMake",
            fields=[
                (
                    "make_id",
                    models.IntegerField(
                        db_column="MAKE_ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "make_nm",
                    models.CharField(
                        blank=True, db_column="MAKE_NM", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "db_table": "dbo.MAKE",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NAGSMakeModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("make_id", models.IntegerField(db_column="MAKE_ID")),
                ("model_id", models.IntegerField(db_column="MODEL_ID")),
                (
                    "model_nm",
                    models.CharField(
                        blank=True, db_column="MODEL_NM", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "db_table": "dbo.MAKE_MODEL",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NAGSPrefix",
            fields=[
                (
                    "prefix_cd",
                    models.CharField(
                        db_column="PREFIX_CD",
                        max_length=2,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dsc",
                    models.CharField(
                        blank=True, db_column="DSC", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "db_table": "dbo.PREFIX",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NAGSVehicle",
            fields=[
                (
                    "veh_id",
                    models.IntegerField(
                        db_column="VEH_ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "make_id",
                    models.IntegerField(blank=True, db_column="MAKE_ID", null=True),
                ),
                (
                    "model_id",
                    models.IntegerField(blank=True, db_column="MODEL_ID", null=True),
                ),
                (
                    "year",
                    models.SmallIntegerField(blank=True, db_column="YEAR", null=True),
                ),
                (
                    "body_style_cd",
                    models.CharField(
                        blank=True, db_column="BODY_STYLE_CD", max_length=2, null=True
                    ),
                ),
            ],
            options={
                "db_table": "dbo.VEH",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NAGSVehicleGlass",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "veh_id",
                    models.IntegerField(
                        db_column="VEH_ID", db_index=True, help_text="FK to VEH table"
                    ),
                ),
                (
                    "nags_glass_id",
                    models.CharField(
                        db_column="NAGS_GLASS_ID",
                        help_text="FK to NAGS_GLASS",
                        max_length=7,
                    ),
                ),
                (
                    "opening_seq",
                    models.SmallIntegerField(
                        db_column="OPENING_SEQ",
                        help_text="Opening sequence (1=primary, 2+=alternates)",
                    ),
                ),
                (
                    "additional_nags_labor",
                    models.CharField(
                        blank=True,
                        db_column="ADDITIONAL_NAGS_LABOR",
                        help_text="Extra labor hours",
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "from_range",
                    models.CharField(
                        blank=True,
                        db_column="FROM_RANGE",
                        help_text="VIN range start",
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "to_range",
                    models.CharField(
                        blank=True,
                        db_column="TO_RANGE",
                        help_text="VIN range end",
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "range_type_cd",
                    models.CharField(
                        blank=True, db_column="RANGE_TYPE_CD", max_length=1, null=True
                    ),
                ),
            ],
            options={
                "db_table": "dbo.VEH_GLASS",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="MockVehicleData",
        ),
    ]
