# Generated by Django 5.1 on 2025-11-22 19:23

import django.db.models.deletion
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('pricing', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vin', models.CharField(max_length=17, verbose_name='VIN')),
                ('vehicle_info', models.JSONField(default=dict)),
                ('postal_code', models.CharField(db_index=True, max_length=20, verbose_name='postal code')),
                ('glass_type', models.CharField(choices=[('windshield', 'Windshield'), ('door_front_left', 'Door Front Left'), ('door_front_right', 'Door Front Right'), ('door_rear_left', 'Door Rear Left'), ('door_rear_right', 'Door Rear Right'), ('back_glass', 'Back Glass'), ('vent_front_left', 'Vent Front Left'), ('vent_front_right', 'Vent Front Right'), ('vent_rear_left', 'Vent Rear Left'), ('vent_rear_right', 'Vent Rear Right')], max_length=50)),
                ('service_type', models.CharField(choices=[('mobile', 'Mobile Service'), ('in_store', 'In-Store Service')], max_length=20)),
                ('service_address', models.JSONField(blank=True, default=dict)),
                ('distance_from_shop_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash/Credit'), ('insurance', 'Insurance')], max_length=20)),
                ('insurance_claim_number', models.CharField(blank=True, max_length=100)),
                ('insurance_deductible', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pricing_details', models.JSONField(default=dict)),
                ('part_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fees', models.JSONField(default=dict)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('state', django_fsm.FSMField(choices=[('draft', 'Draft'), ('pending_validation', 'Pending Validation'), ('sent', 'Sent to Customer'), ('customer_approved', 'Customer Approved'), ('scheduled', 'Appointment Scheduled'), ('converted', 'Converted to Job'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='draft', max_length=50, protected=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('website', 'Website'), ('vapi', 'VAPI Call')], default='website', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='customers.customer')),
                ('insurance_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.insuranceprovider')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('part', 'Part'), ('labor', 'Labor'), ('fee', 'Fee'), ('custom', 'Custom')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='quotes.quote')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteStateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(max_length=50)),
                ('to_state', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='quotes.quote')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['state', 'created_at'], name='quotes_quot_state_794863_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['postal_code', 'service_type'], name='quotes_quot_postal__09814a_idx'),
        ),
    ]
