# Generated by Django 5.1 on 2025-11-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="approval_token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="approval_token_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
