# Generated by Django 5.1 on 2025-11-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0002_quote_approval_token_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="damage_quantity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3+", "3 or more"),
                    ("unknown", "Unknown/Not Specified"),
                ],
                default="unknown",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="damage_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("chip", "Chip(s)"),
                    ("crack", "Crack(s)"),
                    ("both", "Both Chips and Cracks"),
                    ("unknown", "Unknown/Not Specified"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
    ]
