# Generated by Django 5.1 on 2025-11-22 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='provider name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='provider code')),
                ('uses_custom_pricing', models.BooleanField(default=False)),
                ('markup_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('requires_pre_approval', models.BooleanField(default=False)),
                ('average_approval_time_hours', models.PositiveIntegerField(default=24)),
                ('claims_phone', models.CharField(blank=True, max_length=20)),
                ('claims_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_labor_rate', models.DecimalField(decimal_places=2, default=150.0, max_digits=6)),
                ('complex_labor_rate', models.DecimalField(decimal_places=2, default=200.0, max_digits=6)),
                ('environmental_fee', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('disposal_fee', models.DecimalField(decimal_places=2, default=10.0, max_digits=6)),
                ('markup_multiplier', models.DecimalField(decimal_places=2, default=1.3, max_digits=4)),
                ('mobile_fee_tier_1_distance', models.PositiveIntegerField(default=15)),
                ('mobile_fee_tier_1_amount', models.DecimalField(decimal_places=2, default=25.0, max_digits=6)),
                ('mobile_fee_tier_2_distance', models.PositiveIntegerField(default=30)),
                ('mobile_fee_tier_2_amount', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('mobile_fee_tier_3_amount', models.DecimalField(decimal_places=2, default=75.0, max_digits=6)),
                ('max_mobile_service_distance', models.PositiveIntegerField(default=50)),
                ('quote_expiration_days', models.PositiveIntegerField(default=7)),
            ],
            options={
                'verbose_name': 'pricing configuration',
                'verbose_name_plural': 'pricing configuration',
            },
        ),
        migrations.CreateModel(
            name='ShopPricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('pricing_strategy', models.CharField(choices=[('percentage_discount', 'Percentage Discount'), ('fixed_discount', 'Fixed Amount Discount'), ('fixed_price', 'Fixed Price')], max_length=50)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('glass_type', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='shops.shop')),
            ],
            options={
                'ordering': ['-priority'],
                'unique_together': {('shop', 'manufacturer', 'glass_type', 'pricing_strategy')},
            },
        ),
    ]
