# Generated by Django 5.1 on 2025-11-23 01:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingconfig",
            name="markup_multiplier",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("1.30"), max_digits=4
            ),
        ),
    ]
