# Generated by Django 5.1 on 2025-12-06 19:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0002_alter_pricingconfig_markup_multiplier"),
        ("shops", "0002_add_auto_approve_quotes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Default profile for this shop when no specific match",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "price_rule_type",
                    models.CharField(
                        choices=[
                            ("percent_off_list", "% Off Application Provider"),
                            ("flat_amount", "Flat Amount"),
                            ("cost_plus", "Cost Plus"),
                        ],
                        default="percent_off_list",
                        max_length=20,
                    ),
                ),
                (
                    "glass_discount_dw",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("48.00"),
                        help_text="Discount % for DW (Domestic Windshield)",
                        max_digits=5,
                        verbose_name="Domestic Windshield Discount %",
                    ),
                ),
                (
                    "glass_discount_dt",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("48.00"),
                        help_text="Discount % for DT (Domestic Tempered)",
                        max_digits=5,
                        verbose_name="Domestic Tempered Discount %",
                    ),
                ),
                (
                    "glass_discount_fw",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("48.00"),
                        help_text="Discount % for FW (Foreign Windshield)",
                        max_digits=5,
                        verbose_name="Foreign Windshield Discount %",
                    ),
                ),
                (
                    "glass_discount_ft",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("48.00"),
                        help_text="Discount % for FT (Foreign Tempered)",
                        max_digits=5,
                        verbose_name="Foreign Tempered Discount %",
                    ),
                ),
                (
                    "glass_discount_oem",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Discount % for OEM (Original Equipment)",
                        max_digits=5,
                        verbose_name="OEM Discount %",
                    ),
                ),
                (
                    "labor_type",
                    models.CharField(
                        choices=[("flat", "Flat"), ("multiplier", "Multiplier")],
                        default="multiplier",
                        help_text="Flat = fixed amount, Multiplier = hours × rate",
                        max_length=10,
                    ),
                ),
                (
                    "labor_rate_dw",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("44.80"),
                        max_digits=6,
                        verbose_name="DW Labor Rate",
                    ),
                ),
                (
                    "labor_rate_dt",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("44.80"),
                        max_digits=6,
                        verbose_name="DT Labor Rate",
                    ),
                ),
                (
                    "labor_rate_fw",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("44.80"),
                        max_digits=6,
                        verbose_name="FW Labor Rate",
                    ),
                ),
                (
                    "labor_rate_ft",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("44.80"),
                        max_digits=6,
                        verbose_name="FT Labor Rate",
                    ),
                ),
                (
                    "labor_flat_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("44.80"),
                        help_text="Fixed labor charge when labor_type is 'flat'",
                        max_digits=6,
                        verbose_name="Flat Labor Amount",
                    ),
                ),
                (
                    "kit_fee_1_hour",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("23.00"),
                        max_digits=6,
                        verbose_name="Kit Fee (1 hour)",
                    ),
                ),
                (
                    "kit_fee_1_5_hour",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("46.00"),
                        max_digits=6,
                        verbose_name="Kit Fee (1.5 hours)",
                    ),
                ),
                (
                    "kit_fee_2_hour",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("46.00"),
                        max_digits=6,
                        verbose_name="Kit Fee (2 hours)",
                    ),
                ),
                (
                    "kit_fee_2_5_hour",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("46.00"),
                        max_digits=6,
                        verbose_name="Kit Fee (2.5 hours)",
                    ),
                ),
                (
                    "kit_fee_3_plus_hour",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("46.00"),
                        max_digits=6,
                        verbose_name="Kit Fee (3+ hours)",
                    ),
                ),
                (
                    "kit_fee_other",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Optional flat fee for non-standard kits",
                        max_digits=6,
                        verbose_name="Other Kit Fee",
                    ),
                ),
                (
                    "moulding_markup_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Markup percentage on moulding cost",
                        max_digits=5,
                        verbose_name="Moulding Markup %",
                    ),
                ),
                (
                    "moulding_flat_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Alternative flat fee for moulding",
                        max_digits=6,
                        verbose_name="Moulding Flat Fee",
                    ),
                ),
                (
                    "hardware_markup_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Markup percentage on hardware cost",
                        max_digits=5,
                        verbose_name="Hardware Markup %",
                    ),
                ),
                (
                    "hardware_flat_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Alternative flat fee for hardware",
                        max_digits=6,
                        verbose_name="Hardware Flat Fee",
                    ),
                ),
                (
                    "chip_repair_wr1",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("49.00"),
                        help_text="First chip repair price",
                        max_digits=6,
                        verbose_name="Chip #1 (WR-1)",
                    ),
                ),
                (
                    "chip_repair_wr2",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("29.00"),
                        help_text="Second chip repair price",
                        max_digits=6,
                        verbose_name="Chip #2 (WR-2)",
                    ),
                ),
                (
                    "chip_repair_wr3",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("29.00"),
                        help_text="Third and subsequent chips (each)",
                        max_digits=6,
                        verbose_name="Chip #3+ (WR-3)",
                    ),
                ),
                (
                    "crack_repair_cr1",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("59.00"),
                        help_text="Crack repair 0-6 inches",
                        max_digits=6,
                        verbose_name='Crack 0-6" (CR-1)',
                    ),
                ),
                (
                    "crack_repair_cr2",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("79.00"),
                        help_text="Crack repair 6-12 inches",
                        max_digits=6,
                        verbose_name='Crack 6-12" (CR-2)',
                    ),
                ),
                (
                    "crack_repair_cr3",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Crack 12+ inches - typically recommend replacement",
                        max_digits=6,
                        verbose_name='Crack 12+" (CR-3)',
                    ),
                ),
                (
                    "calibration_static",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("195.00"),
                        help_text="Camera calibration with target board in shop",
                        max_digits=6,
                        verbose_name="Static Calibration",
                    ),
                ),
                (
                    "calibration_dynamic",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("295.00"),
                        help_text="Requires road test to recalibrate",
                        max_digits=6,
                        verbose_name="Dynamic Calibration",
                    ),
                ),
                (
                    "calibration_dual",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("395.00"),
                        help_text="Both static AND dynamic required",
                        max_digits=6,
                        verbose_name="Dual Calibration",
                    ),
                ),
                (
                    "mobile_fee_base",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("49.00"),
                        max_digits=6,
                        verbose_name="Mobile Fee (0-30 miles)",
                    ),
                ),
                (
                    "mobile_fee_extended_base",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("49.00"),
                        max_digits=6,
                        verbose_name="Mobile Fee Extended Base (31-60 miles)",
                    ),
                ),
                (
                    "mobile_fee_per_mile",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.50"),
                        help_text="Additional per-mile charge for 31-60 mile range",
                        max_digits=4,
                        verbose_name="Per Mile Fee (31-60 miles)",
                    ),
                ),
                (
                    "mobile_max_distance",
                    models.PositiveIntegerField(
                        default=60, verbose_name="Max Mobile Distance (miles)"
                    ),
                ),
                (
                    "admin_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Fee added for insurance claims",
                        max_digits=6,
                        verbose_name="Admin Fee",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_profiles",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "pricing profile",
                "verbose_name_plural": "pricing profiles",
                "ordering": ["-is_default", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("shop",),
                        name="unique_default_profile_per_shop",
                    )
                ],
            },
        ),
    ]
