# Generated by Django 5.1 on 2025-12-07 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0003_add_pricing_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShopPricingRule",
        ),
    ]
