# Generated by Django 5.1 on 2025-11-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="auto_approve_quotes",
            field=models.BooleanField(
                default=False,
                help_text="Automatically approve and send quotes without review",
            ),
        ),
    ]
