# Generated by Django 5.1 on 2025-12-10 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chatwoot_agent_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Chatwoot agent ID for message attribution",
                        null=True,
                    ),
                ),
                (
                    "chatwoot_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email used in Chatwoot (may differ from Django email)",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "is_chatwoot_synced",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this agent has been synced with Chatwoot",
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this agent was synced with Chatwoot",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Profile",
                "verbose_name_plural": "Agent Profiles",
            },
        ),
    ]
